#THIS file contains things you need to get the OLED.yaml project running on SDL (how i used to test everything before getting real hardware
#HIGHLY OUT OF DATE you're better of modifying the original file to work on sdl 
esphome:
    name: testhost
host:

logger: #0 bauds

api:
#^^^^^^^^^^^^^^^^^^^^^^^^ Remove and replace with autogen from esphome

display:
  - platform: sdl
    id: oled_display
    dimensions:
      width: 128
      height: 64
    update_interval: 100ms


# Input keys FOR SDL
binary_sensor:
  - platform: sdl
    id: key_up
    key: SDLK_a
    on_press:
      then:
        - script.execute: oledoff_timer
        - if:
            condition:
                or:
                - display.is_displaying_page: blank
                - display.is_displaying_page: timemenu                
            then:
              - display_menu.show: menu
            else:
              - display_menu.up: menu

  - platform: sdl
    id: key_down
    key: SDLK_s
    on_press:
      then:
        - script.execute: oledoff_timer
        - if:
            condition:
                or:
                - display.is_displaying_page: blank
                - display.is_displaying_page: timemenu                
            then:
              - display_menu.show: menu
            else:
              - display_menu.down: menu

  - platform: sdl
    id: key_left
    key: SDLK_d
    on_press:
      then:
      - display_menu.show: menu
  - platform: sdl
    id: key_right
    key: SDLK_f
    on_press:
      then:
        - script.execute: oledoff_timer
        - if:
            condition:
                or:
                - display.is_displaying_page: blank
                - display.is_displaying_page: timemenu                
            then:
              - display_menu.show: menu
            else:
              - display_menu.enter: menu
