binary_sensor:
 - platform: gpio
   name: key1
   pin: GPIO8
- platform: gpio
   name: key2
   pin: GPIO8
- platform: gpio
   name: key3
   pin: GPIO8
- platform: gpio
   name: key4
   pin: GPIO8
- platform: gpio
   name: key5
   pin: GPIO8
- platform: gpio
   name: key6
   pin: GPIO8
 